### PR TITLE
Added Jon Sterling's Type Theory blog.

### PR DESCRIPTION
**Pull request by aalhour**
Jon Sterling is an expert on Type Theory.

### CODE REVIEW

**Comment by j2kun** [comment]
I'm a little hesitant because the previous two posts are a year apart. Sitting on it.

**Comment by aalhour** [comment]
I apologise I couldn't understand your remark. Can you please paraphrase?

**Comment by j2kun** [comment]
Most recent post: 2016-06-22
Previous post: **2015**-07-05

I'd like to restrict this to active bloggers, and it's unclear how active this blog is.

**Comment by aalhour** [comment]
Got your point. Feel free to reject the pull request.

**Pull request closed without merging**
