### PR TITLE
Politics: Nate Silver

### PR DESCRIPTION
**Pull request by calchulus**
Politics: Nate Silver

### CODE REVIEW

**Comment by calchulus** [comment]
*Sorry, only the last commit should be relevant, the first two were my internet getting messed up during editing my own branch. Thanks!

**Comment by j2kun** [comment]
So I actually have, as of late, found more and more of Nate Silver's (and 538's) political commentary to be the same kind of vapid talking head nonsense as anyone else in politics. 

Would you be open to recategorizing him under statistics, and linking to a post that's specifically about the difficulties and details of designing/running polls, or at least something more reasonably objective than a defense of his company's product?

**Comment by calchulus** [comment]
I actually agree; I think his statistical work is still quite strong, but the
bias is definitely there now that he's gotten some notoriety haha.

http://fivethirtyeight.com/features/education-not-income-predicted-who-would-vote-for-trump/
This was one distinction about the uneducated/educated dichotomy that he
highlighted pretty early in the process, and it came out to be true.

Also curious, do you only want one submission per person? This list is something
I've always been interested in curating myself, and so I've got a decent amount
of bookmarked people in various fields.
Best,
Calvin







On Fri, Dec 23, 2016 3:35 AM, Jeremy Kun notifications@github.com
wrote:
So I actually have, as of late, found more and more of Nate Silver's (and 538's)
political commentary to be the same kind of vapid talking head nonsense as
anyone else in politics.

Would you be open to recategorizing him under statistics, and linking to a post
that's specifically about the difficulties and details of designing/running
polls, or at least something more reasonably objective than a defense of his
company's product?

**Comment by j2kun** [comment]
@calchulus Feel free to submit as many PRs as you like :) Or fork if you want to start your own list

**Comment by calchulus** [comment]
Cool, currently travelling but will try to get some more in to you by the
end of the week.

Thanks!

**Comment by j2kun** [comment]
OK I'm going to close this PR for now.

**Pull request closed without merging**
