### PR TITLE
Virtual Reality: Michael Abrash

### PR DESCRIPTION
**Pull request by minjaec**

### CODE REVIEW

**Comment by j2kun** [comment]
@minjaec It looks like Abrash hasn't posted here since 2014. Would it be possible to update this PR with a more active VR expert? (Maybe Abrash blogs somewhere else now?) I'm particularly concerned since AR/VR is such a rapidly moving topic these days.

**Comment by minjaec** [comment]
@j2kun He's now posting on the Oculus VR blog, and his most recent post was [Blog — Welcome to the Virtual Age - Oculus](https://www.oculus.com/blog/welcome-to-the-virtual-age?fb_comment_id=906211502821173_906373342804989). Although his Valve blog is still a great resource, he stopped posting there when he moved to Oculus. And he is not as active anymore. Should I close this request and add another, more active blogger? Thanks,

**Comment by j2kun** [comment]
@minjaec yes, I think a more active blogger would be nice. Tentatively, my goal is that everyone on the list posts at least once every 2-3 months.

**Comment by minjaec** [comment]
@j2kun I will close this and submit a new pull request!

**Pull request closed without merging**
